---
requirements: | 
functional:
  - Вывод в виде форматированной таблицы 0.0
  - Принимает данные на вход "sex, age, height, weight". 0.1
  - Выводит количестко нужных продуктов в граммах по формуле расчета БЖУ. 0.2
  - Выводит название продуктов. 0.3
  - Вывод каллорий/БЖУ/соотношение 0.4
  - Выводит разные расчеты для мужчины и женщины при равных параметрах. 0.5
non-functional:
  - Выводит граммовку без плавающей запятой. 1.0
  - Выводит выходные данные на русском языке 1.1
implicit:
  - Названия и значения не выходят за рамки таблицы 2.0
  